// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyumsvXSUWz7esI8hnOfN1JV-Z-VLOPUo',
    appId: '1:958905139300:web:c79802aadaf7ab38fc5f71',
    messagingSenderId: '958905139300',
    projectId: 'hi-app-fc2c4',
    authDomain: 'hi-app-fc2c4.firebaseapp.com',
    storageBucket: 'hi-app-fc2c4.firebasestorage.app',
    measurementId: 'G-P3DCTW8927',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbxdJnOqx4coo3o3fqCJcOKBnGm7DHsPA',
    appId: '1:958905139300:android:dd779581c97c1b24fc5f71',
    messagingSenderId: '958905139300',
    projectId: 'hi-app-fc2c4',
    storageBucket: 'hi-app-fc2c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLmXSA0GWmsWnmKqYfrt7n8-5FE05TZ68',
    appId: '1:958905139300:ios:fedfd010511b1ed5fc5f71',
    messagingSenderId: '958905139300',
    projectId: 'hi-app-fc2c4',
    storageBucket: 'hi-app-fc2c4.firebasestorage.app',
    iosClientId: '958905139300-nle95im7i8ahfbpjnfpft9nbl82ml23f.apps.googleusercontent.com',
    iosBundleId: 'studios.hi.app.hiPseudonymous',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLmXSA0GWmsWnmKqYfrt7n8-5FE05TZ68',
    appId: '1:958905139300:ios:fedfd010511b1ed5fc5f71',
    messagingSenderId: '958905139300',
    projectId: 'hi-app-fc2c4',
    storageBucket: 'hi-app-fc2c4.firebasestorage.app',
    iosClientId: '958905139300-nle95im7i8ahfbpjnfpft9nbl82ml23f.apps.googleusercontent.com',
    iosBundleId: 'studios.hi.app.hiPseudonymous',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyumsvXSUWz7esI8hnOfN1JV-Z-VLOPUo',
    appId: '1:958905139300:web:97b13e2cb2281e43fc5f71',
    messagingSenderId: '958905139300',
    projectId: 'hi-app-fc2c4',
    authDomain: 'hi-app-fc2c4.firebaseapp.com',
    storageBucket: 'hi-app-fc2c4.firebasestorage.app',
    measurementId: 'G-N60QBTMPZY',
  );
}
